name: Go

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21
    - name: Check out code
      uses: actions/checkout@v3

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21
    - name: Check out code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: go mod tidy
    - name: Run tests
      run: go test ./...

